/**
 * generated by Xtext 2.14.0
 */
package smarthome.dsl.validation;

import smarthome.dsl.validation.AbstractDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DslValidator extends AbstractDslValidator {
}
