/**
 * generated by Xtext 2.14.0
 */
package smarthome.dsl;

import smarthome.dsl.AbstractDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DslRuntimeModule extends AbstractDslRuntimeModule {
}
