/*
 * generated by Xtext 2.14.0
 */
package smarthome.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
